// <auto-generated />
using MiApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MiApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MiApp.Asegurados", b =>
                {
                    b.Property<int>("AseguradosEdad")
                        .HasColumnType("int");

                    b.Property<string>("AseguradosName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AseguradosTelefono")
                        .HasColumnType("int");

                    b.Property<int>("IdAsegurado")
                        .HasColumnType("int");

                    b.ToTable("Asegurados");
                });

            modelBuilder.Entity("MiApp.Seguros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SumaAsegurada")
                        .HasColumnType("int");

                    b.Property<int>("SumaPrima")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Seguros");
                });
#pragma warning restore 612, 618
        }
    }
}
